version: '2.2'
services:
  rctf:
    image: redpwn/rctf:${RCTF_GIT_REF}
    restart: always
    ports:
      - '9000:80'
    networks:
      - rctf
    env_file:
      - .env
    environment:
      - PORT=80
    volumes:
      - ./conf.d:/app/conf.d
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:6.0.6
    restart: always
    command: ["redis-server", "--requirepass", "${RCTF_REDIS_PASSWORD}"]
    networks:
      - rctf
    volumes:
      - ./data/rctf-redis:/data
  postgres:
    image: postgres:12.3
    restart: always
    environment:
      - POSTGRES_PASSWORD=${RCTF_DATABASE_PASSWORD}
      - POSTGRES_USER=rctf
      - POSTGRES_DB=rctf
    networks:
      - rctf
    volumes:
      - ./data/rctf-postgres:/var/lib/postgresql/data
  bctf:
    container_name: bctf
    build:
      dockerfile: ./Dockerfile
      context: ../bctf
    ports:
      - "9001:3000"
    restart: always

networks:
  rctf: {}
